package com.base.app.domain.model

data class FilmModel(
    val title: String,
    val year: String,
    val rated: String,
    val release: String,
    val runtime: String,
    val genre: String,
    val director: String,
    val writer: String,
    val actors: String,
    val plot: String,
    val language: String,
    val country: String,
    val awards: String,
    val posterUrl: String,
    val ratings: List<FilmRatingModel>,
    val metaScore: String,
    val imdbRating: String,
    val imdbVotes: String,
    val imdbID: String,
    val type: String,
    val dvd: String,
    val boxOffice: String,
    val production: String,
    val website: String,
    val response: String,
    val errorMessages: String,
)