package com.base.app.presentation.film_detail.model

import com.base.app.domain.model.FilmModel

class FilmUiModel(
    val title: String,
    val year: String,
    val rated: String,
    val release: String,
    val runtime: String,
    val genre: String,
    val director: String,
    val writer: String,
    val actors: String,
    val plot: String,
    val language: String,
    val country: String,
    val awards: String,
    val posterUrl: String,
    val ratings: List<FilmRatingUiModel>,
    val metaScore: String,
    val imdbRating: String,
    val imdbVotes: String,
    val imdbID: String,
    val type: String,
    val dvd: String,
    val boxOffice: String,
    val production: String,
    val website: String,
    val response: String,
    val errorMessages: String,
)

fun FilmUiModel.toDomain() = FilmModel(
    title = this.title,
    year = this.year,
    rated = this.rated,
    release = this.release,
    runtime = this.runtime,
    genre = this.genre,
    director = this.director,
    writer = this.writer,
    actors = this.actors,
    plot = this.plot,
    language = this.language,
    country = this.country,
    awards = this.awards,
    posterUrl = this.posterUrl,
    ratings = this.ratings.toDomain(),
    metaScore = this.metaScore,
    imdbRating = this.imdbRating,
    imdbVotes = this.imdbVotes,
    imdbID = this.imdbID,
    type = this.type,
    dvd = this.dvd,
    boxOffice = this.boxOffice,
    production = this.production,
    website = this.website,
    response = this.response,
    errorMessages = this.errorMessages,
)